#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.672791a51c1d239918562d7a0d4420ec137e6694.name = "Post app user creation (branch old_version_for_CI_7)"

    test_upgrade_from.9197309b79b7eec27353a5237ae80708b869d1fb.name = "Before packaging v2 (branch old_version_for_CI_6)"
