#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.d4c6f8f84bb85514459dbe0ba2b17aafaaec1024.name = "Post app user creation (branch old_version_for_CI_7)"

    test_upgrade_from.2c3165c39178821aa05cfcc39ca53c8aa91253ef.name = "Before packaging v2 (branch old_version_for_CI_6)"
